// Mocks generated by Mockito 5.4.6 from annotations
// in stalvi/test/data/repositories/statistics_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:drift/drift.dart' as _i3;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:stalvi/data/database/app_database.dart' as _i2;
import 'package:stalvi/data/database/daos/statistics_dao.dart' as _i5;
import 'package:stalvi/data/database/tables/transaction_table.dart' as _i12;
import 'package:stalvi/domain/entities/account.dart' as _i9;
import 'package:stalvi/domain/entities/category_statistic.dart' as _i11;
import 'package:stalvi/domain/entities/period_summary.dart' as _i6;
import 'package:stalvi/domain/entities/profile.dart' as _i8;
import 'package:stalvi/domain/repositories/i_account_repository.dart' as _i14;
import 'package:stalvi/domain/repositories/i_profile_repository.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAppDatabase_0 extends _i1.SmartFake implements _i2.AppDatabase {
  _FakeAppDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_1 extends _i1.SmartFake
    implements _i3.DatabaseConnection {
  _FakeDatabaseConnection_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_2 extends _i1.SmartFake
    implements _i3.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_3 extends _i1.SmartFake implements _i3.QueryExecutor {
  _FakeQueryExecutor_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_4 extends _i1.SmartFake
    implements _i4.StreamQueryStore {
  _FakeStreamQueryStore_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_5 extends _i1.SmartFake
    implements _i3.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProfilesTable_6 extends _i1.SmartFake
    implements _i2.$ProfilesTable {
  _Fake$ProfilesTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AccountsTable_7 extends _i1.SmartFake
    implements _i2.$AccountsTable {
  _Fake$AccountsTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$CategoriesTable_8 extends _i1.SmartFake
    implements _i2.$CategoriesTable {
  _Fake$CategoriesTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$SavingsGoalsTable_9 extends _i1.SmartFake
    implements _i2.$SavingsGoalsTable {
  _Fake$SavingsGoalsTable_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$TransactionsTable_10 extends _i1.SmartFake
    implements _i2.$TransactionsTable {
  _Fake$TransactionsTable_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStatisticsDaoManager_11 extends _i1.SmartFake
    implements _i5.StatisticsDaoManager {
  _FakeStatisticsDaoManager_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePeriodSummary_12 extends _i1.SmartFake implements _i6.PeriodSummary {
  _FakePeriodSummary_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_13<T1> extends _i1.SmartFake implements _i7.Future<T1> {
  _FakeFuture_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_14<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.InsertStatement<T1, D1> {
  _FakeInsertStatement_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_15<T extends _i3.Table, D> extends _i1.SmartFake
    implements _i3.UpdateStatement<T, D> {
  _FakeUpdateStatement_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_16<T1 extends _i3.HasResultSet, D>
    extends _i1.SmartFake implements _i3.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_17<FirstT extends _i3.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i3.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseSelectStatement_18<Row> extends _i1.SmartFake
    implements _i3.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_19<T1 extends _i3.Table, D1> extends _i1.SmartFake
    implements _i3.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_20<T> extends _i1.SmartFake implements _i3.Selectable<T> {
  _FakeSelectable_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_21 extends _i1.SmartFake
    implements _i3.GenerationContext {
  _FakeGenerationContext_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfile_22 extends _i1.SmartFake implements _i8.Profile {
  _FakeProfile_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccount_23 extends _i1.SmartFake implements _i9.Account {
  _FakeAccount_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StatisticsDao].
///
/// See the documentation for Mockito's code generation for more information.
class MockStatisticsDao extends _i1.Mock implements _i5.StatisticsDao {
  MockStatisticsDao() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AppDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeAppDatabase_0(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i2.AppDatabase);

  @override
  _i3.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_1(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i3.DatabaseConnection);

  @override
  _i3.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_2(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.DriftDatabaseOptions);

  @override
  _i3.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _i10.dummyValue<_i3.SqlTypes>(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i3.SqlTypes);

  @override
  _i3.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_3(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i3.QueryExecutor);

  @override
  _i4.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_4(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i4.StreamQueryStore);

  @override
  _i3.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_5(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i3.DatabaseConnectionUser);

  @override
  _i2.$ProfilesTable get profiles => (super.noSuchMethod(
        Invocation.getter(#profiles),
        returnValue: _Fake$ProfilesTable_6(
          this,
          Invocation.getter(#profiles),
        ),
      ) as _i2.$ProfilesTable);

  @override
  _i2.$AccountsTable get accounts => (super.noSuchMethod(
        Invocation.getter(#accounts),
        returnValue: _Fake$AccountsTable_7(
          this,
          Invocation.getter(#accounts),
        ),
      ) as _i2.$AccountsTable);

  @override
  _i2.$CategoriesTable get categories => (super.noSuchMethod(
        Invocation.getter(#categories),
        returnValue: _Fake$CategoriesTable_8(
          this,
          Invocation.getter(#categories),
        ),
      ) as _i2.$CategoriesTable);

  @override
  _i2.$SavingsGoalsTable get savingsGoals => (super.noSuchMethod(
        Invocation.getter(#savingsGoals),
        returnValue: _Fake$SavingsGoalsTable_9(
          this,
          Invocation.getter(#savingsGoals),
        ),
      ) as _i2.$SavingsGoalsTable);

  @override
  _i2.$TransactionsTable get transactions => (super.noSuchMethod(
        Invocation.getter(#transactions),
        returnValue: _Fake$TransactionsTable_10(
          this,
          Invocation.getter(#transactions),
        ),
      ) as _i2.$TransactionsTable);

  @override
  _i5.StatisticsDaoManager get managers => (super.noSuchMethod(
        Invocation.getter(#managers),
        returnValue: _FakeStatisticsDaoManager_11(
          this,
          Invocation.getter(#managers),
        ),
      ) as _i5.StatisticsDaoManager);

  @override
  _i7.Stream<double> watchGlobalBalance(String? targetCurrency) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchGlobalBalance,
          [targetCurrency],
        ),
        returnValue: _i7.Stream<double>.empty(),
      ) as _i7.Stream<double>);

  @override
  _i7.Stream<_i6.PeriodSummary> watchPeriodSummaryAggregates({
    DateTime? startDate,
    DateTime? endDate,
    required String? targetCurrency,
    String? accountId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchPeriodSummaryAggregates,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #targetCurrency: targetCurrency,
            #accountId: accountId,
          },
        ),
        returnValue: _i7.Stream<_i6.PeriodSummary>.empty(),
      ) as _i7.Stream<_i6.PeriodSummary>);

  @override
  _i7.Future<_i6.PeriodSummary> getPeriodSummaryAggregates({
    DateTime? startDate,
    DateTime? endDate,
    required String? targetCurrency,
    String? accountId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeriodSummaryAggregates,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #targetCurrency: targetCurrency,
            #accountId: accountId,
          },
        ),
        returnValue: _i7.Future<_i6.PeriodSummary>.value(_FakePeriodSummary_12(
          this,
          Invocation.method(
            #getPeriodSummaryAggregates,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
              #targetCurrency: targetCurrency,
              #accountId: accountId,
            },
          ),
        )),
      ) as _i7.Future<_i6.PeriodSummary>);

  @override
  _i7.Stream<List<_i11.CategoryStatistic>> watchTopCategoriesAggregates(
    DateTime? startDate,
    DateTime? endDate,
    String? targetCurrency, {
    _i12.TransactionType? type = _i12.TransactionType.expense,
    String? accountId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchTopCategoriesAggregates,
          [
            startDate,
            endDate,
            targetCurrency,
          ],
          {
            #type: type,
            #accountId: accountId,
          },
        ),
        returnValue: _i7.Stream<List<_i11.CategoryStatistic>>.empty(),
      ) as _i7.Stream<List<_i11.CategoryStatistic>>);

  @override
  _i7.Future<List<_i11.CategoryStatistic>> getTopCategoriesAggregates(
    DateTime? startDate,
    DateTime? endDate,
    String? targetCurrency, {
    _i12.TransactionType? type = _i12.TransactionType.expense,
    String? accountId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopCategoriesAggregates,
          [
            startDate,
            endDate,
            targetCurrency,
          ],
          {
            #type: type,
            #accountId: accountId,
          },
        ),
        returnValue: _i7.Future<List<_i11.CategoryStatistic>>.value(
            <_i11.CategoryStatistic>[]),
      ) as _i7.Future<List<_i11.CategoryStatistic>>);

  @override
  _i7.Future<List<_i2.Transaction>> getTransactionsForPeriod(
    DateTime? startDate,
    DateTime? endDate, {
    String? accountId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsForPeriod,
          [
            startDate,
            endDate,
          ],
          {#accountId: accountId},
        ),
        returnValue:
            _i7.Future<List<_i2.Transaction>>.value(<_i2.Transaction>[]),
      ) as _i7.Future<List<_i2.Transaction>>);

  @override
  _i7.Future<List<_i5.TransactionWithCategory>>
      getTransactionsWithCategoryForPeriod(
    DateTime? startDate,
    DateTime? endDate, {
    _i12.TransactionType? type = _i12.TransactionType.expense,
    String? accountId,
  }) =>
          (super.noSuchMethod(
            Invocation.method(
              #getTransactionsWithCategoryForPeriod,
              [
                startDate,
                endDate,
              ],
              {
                #type: type,
                #accountId: accountId,
              },
            ),
            returnValue: _i7.Future<List<_i5.TransactionWithCategory>>.value(
                <_i5.TransactionWithCategory>[]),
          ) as _i7.Future<List<_i5.TransactionWithCategory>>);

  @override
  _i7.Stream<T> createStream<T extends Object>(
          _i4.QueryStreamFetcher<T>? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i7.Stream<T>.empty(),
      ) as _i7.Stream<T>);

  @override
  T alias<T, D>(
    _i3.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i10.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);

  @override
  void markTablesUpdated(Iterable<_i3.TableInfo<_i3.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i3.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Stream<Set<_i3.TableUpdate>> tableUpdates(
          [_i3.TableUpdateQuery? query = const _i3.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i7.Stream<Set<_i3.TableUpdate>>.empty(),
      ) as _i7.Stream<Set<_i3.TableUpdate>>);

  @override
  _i7.Future<T> doWhenOpened<T>(
          _i7.FutureOr<T> Function(_i3.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_13<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i7.Future<T>);

  @override
  _i3.InsertStatement<T, D> into<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_14<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i3.InsertStatement<T, D>);

  @override
  _i3.UpdateStatement<Tbl, R> update<Tbl extends _i3.Table, R>(
          _i3.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_15<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i3.UpdateStatement<Tbl, R>);

  @override
  _i3.SimpleSelectStatement<T, R> select<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_16<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.SimpleSelectStatement<T, R>);

  @override
  _i3.JoinedSelectStatement<T, R> selectOnly<T extends _i3.HasResultSet, R>(
    _i3.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_17<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i3.JoinedSelectStatement<T, R>);

  @override
  _i3.BaseSelectStatement<_i3.TypedResult> selectExpressions(
          Iterable<_i3.Expression<Object>>? columns) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectExpressions,
          [columns],
        ),
        returnValue: _FakeBaseSelectStatement_18<_i3.TypedResult>(
          this,
          Invocation.method(
            #selectExpressions,
            [columns],
          ),
        ),
      ) as _i3.BaseSelectStatement<_i3.TypedResult>);

  @override
  _i3.DeleteStatement<T, D> delete<T extends _i3.Table, D>(
          _i3.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_19<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i3.DeleteStatement<T, D>);

  @override
  _i7.Future<int> customUpdate(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<int> customInsert(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i7.Future<int>.value(0),
      ) as _i7.Future<int>);

  @override
  _i7.Future<List<_i3.QueryRow>> customWriteReturning(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i3.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i7.Future<List<_i3.QueryRow>>.value(<_i3.QueryRow>[]),
      ) as _i7.Future<List<_i3.QueryRow>>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelect(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_20<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i3.Selectable<_i3.QueryRow> customSelectQuery(
    String? query, {
    List<_i3.Variable<Object>>? variables = const [],
    Set<_i3.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_20<_i3.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i3.Selectable<_i3.QueryRow>);

  @override
  _i7.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<T> transaction<T>(
    _i7.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_13<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i7.Future<T>);

  @override
  _i7.Future<T> exclusively<T>(_i7.Future<T> Function()? action) =>
      (super.noSuchMethod(
        Invocation.method(
          #exclusively,
          [action],
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #exclusively,
                  [action],
                ),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_13<T>(
              this,
              Invocation.method(
                #exclusively,
                [action],
              ),
            ),
      ) as _i7.Future<T>);

  @override
  _i7.Future<void> batch(_i7.FutureOr<void> Function(_i3.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<T> runWithInterceptor<T>(
    _i7.Future<T> Function()? action, {
    required _i3.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #runWithInterceptor,
          [action],
          {#interceptor: interceptor},
        ),
        returnValue: _i10.ifNotNull(
              _i10.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #runWithInterceptor,
                  [action],
                  {#interceptor: interceptor},
                ),
              ),
              (T v) => _i7.Future<T>.value(v),
            ) ??
            _FakeFuture_13<T>(
              this,
              Invocation.method(
                #runWithInterceptor,
                [action],
                {#interceptor: interceptor},
              ),
            ),
      ) as _i7.Future<T>);

  @override
  _i3.GenerationContext $write(
    _i3.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_21(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_21(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  _i3.GenerationContext $writeUpdateInsertable(
    _i3.TableInfo<_i3.Table, dynamic>? table,
    _i3.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeUpdateInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_21(
          this,
          Invocation.method(
            #$writeUpdateInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i3.GenerationContext);

  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: _i10.dummyValue<String>(
          this,
          Invocation.method(
            #$expandVar,
            [
              start,
              amount,
            ],
          ),
        ),
      ) as String);

  @override
  _i7.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [IProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileRepository extends _i1.Mock
    implements _i13.IProfileRepository {
  MockIProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.Profile> createProfile(_i8.Profile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i7.Future<_i8.Profile>.value(_FakeProfile_22(
          this,
          Invocation.method(
            #createProfile,
            [profile],
          ),
        )),
      ) as _i7.Future<_i8.Profile>);

  @override
  _i7.Future<_i8.Profile?> getProfileById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProfileById,
          [id],
        ),
        returnValue: _i7.Future<_i8.Profile?>.value(),
      ) as _i7.Future<_i8.Profile?>);

  @override
  _i7.Future<_i8.Profile?> getFirstProfile() => (super.noSuchMethod(
        Invocation.method(
          #getFirstProfile,
          [],
        ),
        returnValue: _i7.Future<_i8.Profile?>.value(),
      ) as _i7.Future<_i8.Profile?>);

  @override
  _i7.Future<_i8.Profile> updateProfile(_i8.Profile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i7.Future<_i8.Profile>.value(_FakeProfile_22(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i7.Future<_i8.Profile>);

  @override
  _i7.Future<void> deleteProfile(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [IAccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAccountRepository extends _i1.Mock
    implements _i14.IAccountRepository {
  MockIAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i9.Account> createAccount(_i9.Account? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [account],
        ),
        returnValue: _i7.Future<_i9.Account>.value(_FakeAccount_23(
          this,
          Invocation.method(
            #createAccount,
            [account],
          ),
        )),
      ) as _i7.Future<_i9.Account>);

  @override
  _i7.Future<_i9.Account?> getAccountById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getAccountById,
          [id],
        ),
        returnValue: _i7.Future<_i9.Account?>.value(),
      ) as _i7.Future<_i9.Account?>);

  @override
  _i7.Future<List<_i9.Account>> getAccountsByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountsByUserId,
          [userId],
        ),
        returnValue: _i7.Future<List<_i9.Account>>.value(<_i9.Account>[]),
      ) as _i7.Future<List<_i9.Account>>);

  @override
  _i7.Stream<List<_i9.Account>> watchAccountsByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAccountsByUserId,
          [userId],
        ),
        returnValue: _i7.Stream<List<_i9.Account>>.empty(),
      ) as _i7.Stream<List<_i9.Account>>);

  @override
  _i7.Future<_i9.Account> updateAccount(_i9.Account? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [account],
        ),
        returnValue: _i7.Future<_i9.Account>.value(_FakeAccount_23(
          this,
          Invocation.method(
            #updateAccount,
            [account],
          ),
        )),
      ) as _i7.Future<_i9.Account>);

  @override
  _i7.Future<void> deleteAccount(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> hardDeleteAccount(String? id) => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteAccount,
          [id],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i9.Account?> getDefaultAccount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultAccount,
          [userId],
        ),
        returnValue: _i7.Future<_i9.Account?>.value(),
      ) as _i7.Future<_i9.Account?>);

  @override
  _i7.Future<void> setDefaultAccount(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultAccount,
          [accountId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
