// Mocks generated by Mockito 5.4.6 from annotations
// in stalvi/test/domain/usecases/automatic_transactions/delete_automatic_transaction_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stalvi/domain/entities/automatic_transaction.dart' as _i2;
import 'package:stalvi/domain/repositories/i_automatic_transaction_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAutomaticTransaction_0 extends _i1.SmartFake
    implements _i2.AutomaticTransaction {
  _FakeAutomaticTransaction_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAutomaticTransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAutomaticTransactionRepository extends _i1.Mock
    implements _i3.IAutomaticTransactionRepository {
  @override
  _i4.Future<_i2.AutomaticTransaction> createAutomaticTransaction(
          _i2.AutomaticTransaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAutomaticTransaction,
          [transaction],
        ),
        returnValue: _i4.Future<_i2.AutomaticTransaction>.value(
            _FakeAutomaticTransaction_0(
          this,
          Invocation.method(
            #createAutomaticTransaction,
            [transaction],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.AutomaticTransaction>.value(
            _FakeAutomaticTransaction_0(
          this,
          Invocation.method(
            #createAutomaticTransaction,
            [transaction],
          ),
        )),
      ) as _i4.Future<_i2.AutomaticTransaction>);

  @override
  _i4.Future<_i2.AutomaticTransaction?> getAutomaticTransactionById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAutomaticTransactionById,
          [id],
        ),
        returnValue: _i4.Future<_i2.AutomaticTransaction?>.value(),
        returnValueForMissingStub:
            _i4.Future<_i2.AutomaticTransaction?>.value(),
      ) as _i4.Future<_i2.AutomaticTransaction?>);

  @override
  _i4.Future<List<_i2.AutomaticTransaction>> getAllAutomaticTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAutomaticTransactions,
          [],
        ),
        returnValue: _i4.Future<List<_i2.AutomaticTransaction>>.value(
            <_i2.AutomaticTransaction>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.AutomaticTransaction>>.value(
                <_i2.AutomaticTransaction>[]),
      ) as _i4.Future<List<_i2.AutomaticTransaction>>);

  @override
  _i4.Stream<List<_i2.AutomaticTransaction>> watchAllAutomaticTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllAutomaticTransactions,
          [],
        ),
        returnValue: _i4.Stream<List<_i2.AutomaticTransaction>>.empty(),
        returnValueForMissingStub:
            _i4.Stream<List<_i2.AutomaticTransaction>>.empty(),
      ) as _i4.Stream<List<_i2.AutomaticTransaction>>);

  @override
  _i4.Future<_i2.AutomaticTransaction> updateAutomaticTransaction(
          _i2.AutomaticTransaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAutomaticTransaction,
          [transaction],
        ),
        returnValue: _i4.Future<_i2.AutomaticTransaction>.value(
            _FakeAutomaticTransaction_0(
          this,
          Invocation.method(
            #updateAutomaticTransaction,
            [transaction],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.AutomaticTransaction>.value(
            _FakeAutomaticTransaction_0(
          this,
          Invocation.method(
            #updateAutomaticTransaction,
            [transaction],
          ),
        )),
      ) as _i4.Future<_i2.AutomaticTransaction>);

  @override
  _i4.Future<void> deleteAutomaticTransaction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAutomaticTransaction,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
