// Mocks generated by Mockito 5.4.6 from annotations
// in stalvi/test/domain/usecases/execute_recurring_transactions_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:stalvi/domain/entities/account.dart' as _i5;
import 'package:stalvi/domain/entities/automatic_transaction.dart' as _i2;
import 'package:stalvi/domain/entities/exchange_rate.dart' as _i7;
import 'package:stalvi/domain/entities/profile.dart' as _i6;
import 'package:stalvi/domain/entities/transaction.dart' as _i3;
import 'package:stalvi/domain/repositories/i_account_repository.dart' as _i10;
import 'package:stalvi/domain/repositories/i_automatic_transaction_repository.dart'
    as _i8;
import 'package:stalvi/domain/repositories/i_exchange_rate_repository.dart'
    as _i12;
import 'package:stalvi/domain/repositories/i_profile_repository.dart' as _i11;
import 'package:stalvi/domain/repositories/i_transaction_repository.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAutomaticTransaction_0 extends _i1.SmartFake
    implements _i2.AutomaticTransaction {
  _FakeAutomaticTransaction_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransaction_1 extends _i1.SmartFake implements _i3.Transaction {
  _FakeTransaction_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransferPair_2 extends _i1.SmartFake implements _i4.TransferPair {
  _FakeTransferPair_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAccount_3 extends _i1.SmartFake implements _i5.Account {
  _FakeAccount_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfile_4 extends _i1.SmartFake implements _i6.Profile {
  _FakeProfile_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeExchangeRate_5 extends _i1.SmartFake implements _i7.ExchangeRate {
  _FakeExchangeRate_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [IAutomaticTransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAutomaticTransactionRepository extends _i1.Mock
    implements _i8.IAutomaticTransactionRepository {
  MockIAutomaticTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i2.AutomaticTransaction> createAutomaticTransaction(
          _i2.AutomaticTransaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAutomaticTransaction,
          [transaction],
        ),
        returnValue: _i9.Future<_i2.AutomaticTransaction>.value(
            _FakeAutomaticTransaction_0(
          this,
          Invocation.method(
            #createAutomaticTransaction,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i2.AutomaticTransaction>);

  @override
  _i9.Future<_i2.AutomaticTransaction?> getAutomaticTransactionById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAutomaticTransactionById,
          [id],
        ),
        returnValue: _i9.Future<_i2.AutomaticTransaction?>.value(),
      ) as _i9.Future<_i2.AutomaticTransaction?>);

  @override
  _i9.Future<List<_i2.AutomaticTransaction>> getAllAutomaticTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllAutomaticTransactions,
          [],
        ),
        returnValue: _i9.Future<List<_i2.AutomaticTransaction>>.value(
            <_i2.AutomaticTransaction>[]),
      ) as _i9.Future<List<_i2.AutomaticTransaction>>);

  @override
  _i9.Stream<List<_i2.AutomaticTransaction>> watchAllAutomaticTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllAutomaticTransactions,
          [],
        ),
        returnValue: _i9.Stream<List<_i2.AutomaticTransaction>>.empty(),
      ) as _i9.Stream<List<_i2.AutomaticTransaction>>);

  @override
  _i9.Future<_i2.AutomaticTransaction> updateAutomaticTransaction(
          _i2.AutomaticTransaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAutomaticTransaction,
          [transaction],
        ),
        returnValue: _i9.Future<_i2.AutomaticTransaction>.value(
            _FakeAutomaticTransaction_0(
          this,
          Invocation.method(
            #updateAutomaticTransaction,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i2.AutomaticTransaction>);

  @override
  _i9.Future<void> deleteAutomaticTransaction(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAutomaticTransaction,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [ITransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransactionRepository extends _i1.Mock
    implements _i4.ITransactionRepository {
  MockITransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i3.Transaction> createTransaction(_i3.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransaction,
          [transaction],
        ),
        returnValue: _i9.Future<_i3.Transaction>.value(_FakeTransaction_1(
          this,
          Invocation.method(
            #createTransaction,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i3.Transaction>);

  @override
  _i9.Future<_i4.TransferPair> createTransferPair({
    required _i3.Transaction? originTransaction,
    required _i3.Transaction? destinationTransaction,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTransferPair,
          [],
          {
            #originTransaction: originTransaction,
            #destinationTransaction: destinationTransaction,
          },
        ),
        returnValue: _i9.Future<_i4.TransferPair>.value(_FakeTransferPair_2(
          this,
          Invocation.method(
            #createTransferPair,
            [],
            {
              #originTransaction: originTransaction,
              #destinationTransaction: destinationTransaction,
            },
          ),
        )),
      ) as _i9.Future<_i4.TransferPair>);

  @override
  _i9.Future<_i3.Transaction?> getTransactionById(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionById,
          [id],
        ),
        returnValue: _i9.Future<_i3.Transaction?>.value(),
      ) as _i9.Future<_i3.Transaction?>);

  @override
  _i9.Future<List<_i3.Transaction>> getTransactionsByAccountId(
          String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTransactionsByAccountId,
          [accountId],
        ),
        returnValue:
            _i9.Future<List<_i3.Transaction>>.value(<_i3.Transaction>[]),
      ) as _i9.Future<List<_i3.Transaction>>);

  @override
  _i9.Future<_i3.Transaction> updateTransaction(_i3.Transaction? transaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTransaction,
          [transaction],
        ),
        returnValue: _i9.Future<_i3.Transaction>.value(_FakeTransaction_1(
          this,
          Invocation.method(
            #updateTransaction,
            [transaction],
          ),
        )),
      ) as _i9.Future<_i3.Transaction>);

  @override
  _i9.Future<void> deleteTransaction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTransaction,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> hardDeleteTransaction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteTransaction,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> restoreTransaction(String? id) => (super.noSuchMethod(
        Invocation.method(
          #restoreTransaction,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> softDeleteTransactionsByAccountId(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteTransactionsByAccountId,
          [accountId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> hardDeleteTransactionsByAccountId(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #hardDeleteTransactionsByAccountId,
          [accountId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Stream<List<_i3.Transaction>> watchRawTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchRawTransactions,
          [],
        ),
        returnValue: _i9.Stream<List<_i3.Transaction>>.empty(),
      ) as _i9.Stream<List<_i3.Transaction>>);

  @override
  _i9.Stream<List<_i3.Transaction>> watchAllTransactions() =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllTransactions,
          [],
        ),
        returnValue: _i9.Stream<List<_i3.Transaction>>.empty(),
      ) as _i9.Stream<List<_i3.Transaction>>);

  @override
  _i9.Stream<List<_i3.Transaction>> watchFilteredTransactions(
          _i4.TransactionQueryFilter? filter) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchFilteredTransactions,
          [filter],
        ),
        returnValue: _i9.Stream<List<_i3.Transaction>>.empty(),
      ) as _i9.Stream<List<_i3.Transaction>>);
}

/// A class which mocks [IAccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAccountRepository extends _i1.Mock
    implements _i10.IAccountRepository {
  MockIAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i5.Account> createAccount(_i5.Account? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAccount,
          [account],
        ),
        returnValue: _i9.Future<_i5.Account>.value(_FakeAccount_3(
          this,
          Invocation.method(
            #createAccount,
            [account],
          ),
        )),
      ) as _i9.Future<_i5.Account>);

  @override
  _i9.Future<_i5.Account?> getAccountById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getAccountById,
          [id],
        ),
        returnValue: _i9.Future<_i5.Account?>.value(),
      ) as _i9.Future<_i5.Account?>);

  @override
  _i9.Future<List<_i5.Account>> getAccountsByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAccountsByUserId,
          [userId],
        ),
        returnValue: _i9.Future<List<_i5.Account>>.value(<_i5.Account>[]),
      ) as _i9.Future<List<_i5.Account>>);

  @override
  _i9.Stream<List<_i5.Account>> watchAccountsByUserId(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAccountsByUserId,
          [userId],
        ),
        returnValue: _i9.Stream<List<_i5.Account>>.empty(),
      ) as _i9.Stream<List<_i5.Account>>);

  @override
  _i9.Future<_i5.Account> updateAccount(_i5.Account? account) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [account],
        ),
        returnValue: _i9.Future<_i5.Account>.value(_FakeAccount_3(
          this,
          Invocation.method(
            #updateAccount,
            [account],
          ),
        )),
      ) as _i9.Future<_i5.Account>);

  @override
  _i9.Future<void> deleteAccount(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<void> hardDeleteAccount(String? id) => (super.noSuchMethod(
        Invocation.method(
          #hardDeleteAccount,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);

  @override
  _i9.Future<_i5.Account?> getDefaultAccount(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDefaultAccount,
          [userId],
        ),
        returnValue: _i9.Future<_i5.Account?>.value(),
      ) as _i9.Future<_i5.Account?>);

  @override
  _i9.Future<void> setDefaultAccount(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #setDefaultAccount,
          [accountId],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [IProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIProfileRepository extends _i1.Mock
    implements _i11.IProfileRepository {
  MockIProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i6.Profile> createProfile(_i6.Profile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i9.Future<_i6.Profile>.value(_FakeProfile_4(
          this,
          Invocation.method(
            #createProfile,
            [profile],
          ),
        )),
      ) as _i9.Future<_i6.Profile>);

  @override
  _i9.Future<_i6.Profile?> getProfileById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getProfileById,
          [id],
        ),
        returnValue: _i9.Future<_i6.Profile?>.value(),
      ) as _i9.Future<_i6.Profile?>);

  @override
  _i9.Future<_i6.Profile?> getFirstProfile() => (super.noSuchMethod(
        Invocation.method(
          #getFirstProfile,
          [],
        ),
        returnValue: _i9.Future<_i6.Profile?>.value(),
      ) as _i9.Future<_i6.Profile?>);

  @override
  _i9.Future<_i6.Profile> updateProfile(_i6.Profile? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i9.Future<_i6.Profile>.value(_FakeProfile_4(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i9.Future<_i6.Profile>);

  @override
  _i9.Future<void> deleteProfile(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteProfile,
          [id],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}

/// A class which mocks [IExchangeRateRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIExchangeRateRepository extends _i1.Mock
    implements _i12.IExchangeRateRepository {
  MockIExchangeRateRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i9.Future<_i7.ExchangeRate> getLatestRates(
          {required String? baseCurrency}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLatestRates,
          [],
          {#baseCurrency: baseCurrency},
        ),
        returnValue: _i9.Future<_i7.ExchangeRate>.value(_FakeExchangeRate_5(
          this,
          Invocation.method(
            #getLatestRates,
            [],
            {#baseCurrency: baseCurrency},
          ),
        )),
      ) as _i9.Future<_i7.ExchangeRate>);

  @override
  _i9.Future<_i7.ExchangeRate?> getLocalRates(
          {required String? baseCurrency}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalRates,
          [],
          {#baseCurrency: baseCurrency},
        ),
        returnValue: _i9.Future<_i7.ExchangeRate?>.value(),
      ) as _i9.Future<_i7.ExchangeRate?>);

  @override
  _i9.Future<void> syncRates({required String? baseCurrency}) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncRates,
          [],
          {#baseCurrency: baseCurrency},
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
