// Mocks generated by Mockito 5.4.6 from annotations
// in stalvi/test/unit/auth_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:stalvi/core/security/secure_storage_manager.dart' as _i2;
import 'package:stalvi/infrastructure/services/biometric_auth_service.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SecureStorageManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageManager extends _i1.Mock
    implements _i2.SecureStorageManager {
  MockSecureStorageManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getOrCreateEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #getOrCreateEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getOrCreateEncryptionKey,
            [],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<bool> hasEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #hasEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deleteEncryptionKey() => (super.noSuchMethod(
        Invocation.method(
          #deleteEncryptionKey,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getUserLocale() => (super.noSuchMethod(
        Invocation.method(
          #getUserLocale,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setUserLocale(String? languageCode) => (super.noSuchMethod(
        Invocation.method(
          #setUserLocale,
          [languageCode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> savePinHash(String? pinHash) => (super.noSuchMethod(
        Invocation.method(
          #savePinHash,
          [pinHash],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> getPinHash() => (super.noSuchMethod(
        Invocation.method(
          #getPinHash,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<bool> hasPin() => (super.noSuchMethod(
        Invocation.method(
          #hasPin,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> deletePinHash() => (super.noSuchMethod(
        Invocation.method(
          #deletePinHash,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> savePinLength(int? length) => (super.noSuchMethod(
        Invocation.method(
          #savePinLength,
          [length],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int?> getPinLength() => (super.noSuchMethod(
        Invocation.method(
          #getPinLength,
          [],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  _i3.Future<void> deletePinLength() => (super.noSuchMethod(
        Invocation.method(
          #deletePinLength,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setBiometricsEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #setBiometricsEnabled,
          [enabled],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isBiometricsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricsEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> hasBiometricsChoice() => (super.noSuchMethod(
        Invocation.method(
          #hasBiometricsChoice,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<String?> getThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getThemeMode,
          [],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> setThemeMode(String? themeMode) => (super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [themeMode],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveLockoutTimestamp(int? epochMs) => (super.noSuchMethod(
        Invocation.method(
          #saveLockoutTimestamp,
          [epochMs],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<int?> getLockoutTimestamp() => (super.noSuchMethod(
        Invocation.method(
          #getLockoutTimestamp,
          [],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  _i3.Future<void> deleteLockoutTimestamp() => (super.noSuchMethod(
        Invocation.method(
          #deleteLockoutTimestamp,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAll() => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [BiometricAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBiometricAuthService extends _i1.Mock
    implements _i5.BiometricAuthService {
  MockBiometricAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> isBiometricAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricAvailable,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> authenticate({
    required String? localizedReason,
    required String? lockedOutMessage,
    required String? authFailedMessage,
    required String? unknownErrorMessage,
    String? signInTitle,
    String? cancelButton,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
          {
            #localizedReason: localizedReason,
            #lockedOutMessage: lockedOutMessage,
            #authFailedMessage: authFailedMessage,
            #unknownErrorMessage: unknownErrorMessage,
            #signInTitle: signInTitle,
            #cancelButton: cancelButton,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<void> enableBiometrics() => (super.noSuchMethod(
        Invocation.method(
          #enableBiometrics,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> disableBiometrics() => (super.noSuchMethod(
        Invocation.method(
          #disableBiometrics,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<bool> isBiometricsEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricsEnabled,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
